name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: bazel-contrib/setup-bazel@0.10.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ runner.os }}-${{ env.cache-name }}
          # Share repository cache between workflows.
          repository-cache: true
      - uses: actions/checkout@v3.5.2
      - name: Build the code
        run: bazel build //...
